baseurl: https://blog.xpdbk.com #å¡«ä½ çš„ç½‘ç«™åœ°å€awa
languageCode: zh-cn
theme: hugo-theme-stack
paginate: 5 # æ¯é¡µæ˜¾ç¤ºå¤šå°‘æ–‡ç« 
title: XiaoPangã®å°å±‹
enableRobotsTXT: true
enableEmoji: true
enableGitInfo: true
uglyURLs: false

languages:
    zh-cn:
        languageName: ä¸­æ–‡
        title: XiaoPangçš„ä¸ªäººåšå®¢
        description: XiaoPangLEl_FENGçš„ä¸ªäººåšå®¢,2b2tçš„ç©å®¶,1.8.9çš„ç©å®¶
        weight: 1
    en:
        languageName: English
        title: XiaoPang Blog
        description: XiaoPang,LEl_FENG,Blog,1.8.9,2b2t,pvp,minecraft
        weight: 2

# ä½¿ç”¨å‰å°†å…¶æ›´æ”¹ä¸ºæ‚¨çš„ Disqus çŸ­åç§°
disqusShortname: abaaba-cyou

# Google Analyticsï¼ˆåˆ†æï¼‰è·Ÿè¸ª ID
googleAnalytics: G-F7BV1R4CWR

# ä¸»é¢˜å›½é™…åŒ–æ”¯æŒ
# å¯ç”¨å€¼ï¼šar, bn, ca, de, el, en, es, fr, hu, id, it, ja, ko, nl, pt-br, th, uk, zh-cn, zh-hk, zh- tw
DefaultContentLanguage: zh-cn

# å¦‚æœ DefaultContentLanguage åœ¨ [zh-cn image] ä¸­ï¼Œåˆ™å°† hasCJKLanguage è®¾ç½®ä¸º true
# è¿™å°†ä½¿ .Summary å’Œ .WordCount å¯¹ CJK è¯­è¨€æ­£ç¡®è¿è¡Œã€‚
hasCJKLanguage: true

permalinks:
    post: /post/:slug
    page: /:slug

params:
    mainSections:
        - post #è®¾ç½®ç½‘ç«™é¦–é¡µè¦å±•ç¤ºçš„Sectionï¼Œä¸€èˆ¬è®¾æˆpostã€‚è¿™æ ·å°±ä¼šé»˜è®¤å±•ç¤ºpostæ–‡ä»¶å¤¹é‡Œé¢çš„å†…å®¹ã€‚
    featuredImageField: image
    rssFullContent: true
    favicon: /favicon.ico

    footer:
        since: 2022
        customText: <a href="https://shengming.xpdbk.com/" target="_blank" >æœ¬ç«™å£°æ˜</a>
                    <a href="https://blog.xpdbk.com/sitemap.xml" target="_blank" >ç«™ç‚¹åœ°å›¾</a>
                    <a href="https://blog.xpdbk.com/index.xml" target="_blank" >RSSè®¢é˜…</a>

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar: #å·¦è¾¹æ 
        compact: false
        emoji: ğŸ˜†â€
        subtitle: è¿½éšæ¢¦æƒ³éœ€ç«­å°½å…¨åŠ›
        avatar:
            enabled: true
            local: true
            src: img/avatar.jpg

    article:
        math: false # è¿™é‡Œå…³é—­æ˜¯å› ä¸ºæˆ‘ä»¬ä½¿ç”¨çš„æ˜¯ MathJax
        toc: true
        readingTime: true
        license:
            enabled: true
            default: Licensed under CC BY-NC-SA 4.0 è½¬è½½æˆ–å¼•ç”¨æœ¬æ–‡æ—¶è¯·éµå®ˆè®¸å¯åè®®ï¼Œå¹¶æ³¨æ˜å‡ºå¤„ä¸å¾—ç”¨äºå•†ä¸šç”¨é€”ï¼

    comments: #è¯„è®º
        enabled: false
        provider: waline

        disqusjs:
            shortname:
            apiUrl:
            apiKey:
            admin:
            adminLabel:

        utterances:
            repo:
            issueTerm: pathname
            label:

        remark42:
            host:
            site:
            locale:

        vssue:
            platform:
            owner:
            repo:
            clientId:
            clientSecret:
            autoCreateIssue: false

        # Walineå®¢æˆ·ç«¯é…ç½®è§ï¼šhttps://waline.js.org/en/reference/component.html
        waline:
            serverURL: https://pl.xpdbk.com
            lang: zh-CN
            pageview: false
            emoji:
                - https://unpkg.com/@waline/emojis@1.0.1/weibo
            requiredMeta:
                - name
                - email
                - url
            locale:
                admin: ç®¡ç†å‘˜
                placeholder: æœ‰ä»€ä¹ˆé—®é¢˜è¯·è¯„è®º

        twikoo:
            envId:
            region:
            path:
            lang:

        # æœ‰å…³å„ç§é€‰é¡¹çš„æè¿°ï¼Œè¯·å‚é˜… https://cactus.chat/docs/reference/web-client/#configuration
        cactus:
            defaultHomeserverUrl: "https://matrix.cactus.chat:8448"
            serverName: "cactus.chat"
            siteName: "" # æ‚¨å¿…é¡»åœ¨æ­¤å¤„æ’å…¥ä¸€ä¸ªä¸æ‚¨æ³¨å†Œçš„æ ‡è¯†ç¬¦åŒ¹é…çš„å”¯ä¸€æ ‡è¯†ç¬¦ï¼ˆå‚è§ https://cactus.chat/docs/getting-started/quick-start/#register-your-siteï¼‰

        giscus:
            repo:
            repoID:
            category:
            categoryID:
            mapping:
            lightTheme:
            darkTheme:
            reactionsEnabled: 1
            emitMetadata: 0

        gitalk:
            owner:
            admin:
            repo:
            clientID:
            clientSecret:

        cusdis:
            host:
            id:
    widgets: #å³è¾¹çš„å°éƒ¨ä»¶ã€‚æ³¨æ„searchå’Œarchivesè¿˜è¦è¿›ä¸€æ­¥è®¾ç½®æ‰èƒ½ä½¿ç”¨ï¼Œå‚è§å‰æ–‡
        homepage:
            - type: search
            - type: archives
              params:
                  limit: 2
            - type: categories
              params:
                  limit: 7
            - type: tag-cloud
              params:
                  limit: 2
        page:
            - type: toc

    opengraph:
        twitter:
            # ä½ çš„æ¨ç‰¹ç”¨æˆ·å
            site: HuaweiH45278254

            # å¯ç”¨å€¼ï¼šsummary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: true
            local: true
            src: img/default.jpg

    colorScheme:
        # æ˜¾ç¤ºåˆ‡æ¢
        toggle: true

        # å¯ç”¨å€¼ï¼šautoã€lightã€dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

###è‡ªå®šä¹‰èœå•
### å‚è§ https://docs.stack.jimmycai.com/configuration/custom-menu.html
### è¦åˆ é™¤å…³äºã€å­˜æ¡£å’Œæœç´¢é¡µé¢çš„èœå•é¡¹ï¼Œè¯·ä»å…¶ FrontMatter ä¸­åˆ é™¤ `menu` å­—æ®µ
menu:
    main: []
  
    social:
    - identifier: github
      name: GitHub
      url: https://github.com/1x000 #é“¾æ¥ï¼Œæ–‡ä»¶å¤¹çš„ç›¸å¯¹ä½ç½®å³å¯ã€‚
      params:
        icon: brand-github
      newTab: true
    - identifier: bilibili
      name: Bilibili
      url: https://space.bilibili.com/698092884
      params:
        icon: icons8-bilibili
      newTab: true
    - identifier: Youtube
      name: Youtube
      url: https://www.youtube.com/channel/UC6dL-SWu0VRfXOkUyCUF70Q
      params:
        icon: YouTube
      newTab: true
    - identifier: telegram
      name: TG
      url: https://t.me/LLLLLawa
      params:
        icon: Telegram_(software)-Logo.wine
      newTab: true
    - identifier: email
      name: Email
      url: mailto:huaweilaomke402@gmail.com
      params:
        icon: mail
      newTab: true

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    goldmark:
        renderer:
            ## å¦‚æœ Markdown ä¸­æœ‰ HTML å†…å®¹ï¼Œåˆ™è®¾ç½®ä¸º true
            unsafe: true
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    highlight:
        noClasses: false
        codeFences: true
        guessSyntax: true
        lineNoStart: 1
        lineNos: true
        lineNumbersInTable: true
        tabWidth: 4